### ISSUE TITLE
Release artifacts should not be split by type

### ISSUE THREAD

**Issue by Anuken** [Sonnicon/mindustry-modtemplate#2]
The non-dexed JAR should not be uploaded to releases, as the dexed version works for both platforms. The file size difference is tiny, and there's no reason to upload two different versions.

The main reason I care about this is that it will break mod importing from the client - with two jars to pick from, it's not clear which is the correct one, and there's no reason to have two in the first place.

Proposed soution: Remove [this block](https://github.com/Sonnicon/mindustry-modtemplate/blob/master/.github/workflows/gradle.yml#L31), and remove the "dexed-" jar prefix from the other artifact.

**Comment by Sonnicon** [comment]
Very well. Although for smaller mods the size difference can be significant, the advantages here outweigh the downsides. Closed by 137569d.
