### ISSUE TITLE
d8 --min-api incorrectly configured

### ISSUE THREAD

**Issue by Anuken** [Sonnicon/mindustry-modtemplate#5]
This template sets d8's `min-api` to be `26`, which is significantly higher than Mindustry's minimum API level (`14`). Roughly 25% of Android phones have an API level below 26, meaning that jar mods produced with this template will not work on 25% of devices - upon import, a cryptic "unknown dex version" error will be shown in the stack trace. [Here's an issue directly caused by this.](https://github.com/sk7725/BetaMindy/issues/24)

Yes, `d8` complains about missing classes at API <26, but that's only because no dependencies are provided. Class files cannot be desugared correctly without these.

A solution to this problem can be seen in [BetaMindy's gradle script](https://github.com/sk7725/BetaMindy/blob/master/build.gradle#L53-L61).

**Comment by Sonnicon** [comment]
Solved by 24c524488ef2aadaf4a734acb5b3d53e36c2bb97. Thank you, closing.
